[package]
name = "opengl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#![feature(core_intrinsics)]

[dependencies]
sdl2 = "0.33"
gl = "0.14.0"